baseURL = 'https://thankful-forest-0bc313e00.5.azurestaticapps.net/'
languageCode = 'ja_JP'
defaultContentLanguage = 'ja'
title = 'Colorkrew(カラクル)'
description = '株式会社Colorkrew(カラクル)の公式コーポレートサイト。「Color Your Work with Excitement」というビジョンのもと、カラフルなチームが、ITで世界にたのしいカラクリをうみだしとどけます！'
hasCJKLanguage = true